### ISSUE TITLE
Backport c258349f1a56b987fd91a5c136fd15536eec3890

### ISSUE THREAD

**Issue by marcosfrm** [lnykryn/systemd-rhel#104]
Since RHEL defaults to XFS, systemd-tmpfiles "Cannot set file attribute for '/var/log/journal', value=0x00800000, mask=0x00800000: Operation not supported" warning messages are just confusing.

https://github.com/systemd/systemd/commit/c258349f1a56b987fd91a5c136fd15536eec3890

**Comment by jsynacek** [comment]
There is no such code in the current RHEL-7.4.
