### ISSUE TITLE
Add spec-file to the repository

### ISSUE THREAD

**Issue by lemenkov** [lnykryn/systemd-rhel#3]
Please consider adding spec-file to the repository as well. Thus we'll have everything required to build a package in one repo. This not only simplifies a building process with modern services like @buildbot but also makes the entire process even more transparent.

**Comment by lnykryn** [comment]
Hmm, I need to think about this. I really like my current setup where spec file is generated by a script directly from a git before building a package, but that script contains a lot of internal stuff.
But maybe it would be nice for every release upload srpm and spec somewhere and use it as a source for copr build, which has a more usable buildroot.

**Comment by jsynacek** [comment]
IMO, this doesn't make sense. We use this repo as sort of a "midstream", which means it stands between the downstream (RHEL7 git repo) and the systemd upstream repo. The spec is purely a downstream thing and is half-independent on this repo, it would be a real pain to properly push spec update commits.
