### ISSUE TITLE
Backport `Type=exec` service type

### ISSUE THREAD

**Issue by mrc0mmand** [lnykryn/systemd-rhel#306]
Relevant PR: https://github.com/systemd/systemd/pull/9620
Test commits depending on this change:
 - [TEST-23-TYPE-EXEC] systemd/systemd@0e1f17561f5f6061ec5503de044298372ed7ca37 (is part of the aforementioned PR)
 - [TEST-23-TYPE-EXEC] systemd/systemd@dd75c133d81f07c56c82ee4e7a80f391ffebd9ce
 - [TEST-23-TYPE-EXEC] systemd/systemd@056ae88152a722bdbea54ff33db815d585c8b9c6
 - [TEST-27-STDOUTFILE] systemd/systemd@196b0a11f306b8041e35316feb05ed1f00380957
 - [TEST-27-STDOUTFILE] systemd/systemd@324ca05459422b55cb6fa04318552541159c239a

cc @msekletar

**Comment by msekletar** [comment]
Thanks for looking up the patches that we need to pull down!
