### ISSUE TITLE
Backport fixes for CapabilityBoundingSet parsing issues

### ISSUE THREAD

**Issue by rewolf** [lnykryn/systemd-rhel#87]
Would it be possible to backport these fixes?
https://github.com/systemd/systemd/pull/1695/commits
https://github.com/systemd/systemd/pull/1713/commits
They're fixes from 2015 and resolve a problem with the config parsing of capabilities

commit https://github.com/systemd/systemd/commit/65dce26488030eff078c498673d5d93e3c87b6a1 
is also small and probably backportable at the same time

**Comment by lnykryn** [comment]
I think that some of those were already backported https://github.com/lnykryn/systemd-rhel/pull/72
But the rest will come, I am currently working on backport for ambient capabilities and effectively that means to backport everything related to capabilities.

**Comment by rewolf** [comment]
@lnykryn Thank you, you're a champion! We're actually using CentOS.  Do the same changes eventually make their way into CentOS from here?

**Comment by lnykryn** [comment]
Yep, but it will take some time.
By the way, we also prepare builds of our staging branch for next release, if you want to test it:
https://copr.fedorainfracloud.org/coprs/lnykryn/systemd-rhel-staging/
But we only do limited testing on them.

**Comment by jsynacek** [comment]
Fixed in RHEL-7.4.
